FROM jfrog-docker-reg2.bintray.io/jfrog/artifactory-pro

MAINTAINER Fabio Sforza <fabio.sforza@relatech.com>

### Add postgres jdbc driver
RUN curl -o /var/opt/jfrog/artifactory/tomcat/lib/postgresql-9.4-1206-jdbc41.jar https://jdbc.postgresql.org/download/postgresql-9.4-1206-jdbc41.jar